clc
clear




% generate clarabel mex interface
mex -v clarabel_mex.cpp ...
        -DFEATURE_SDP ...
      '-I./eigen' ...
       -I"C:\Users\ac133867\Desktop\clarabel_mex_beta\clarabel_mex\clarabel\include" ...
         "C:\Users\ac133867\Desktop\clarabel_mex_beta\clarabel_mex\clarabel\clarabel_c.dll.lib" ...
             "C:\Users\ac133867\Desktop\clarabel_mex_beta\clarabel_mex\clarabel\clarabel_c.lib"
